### ISSUE TITLE
Merging patch from other fork

### ISSUE THREAD

**Issue by allan-simon** [Shougo/javacomplete#2]
Hello

As you seems to have a long standing fork of the javacomplete plugin, I would like to know if you plan to merge the different other forks (I mean check if they don't have interesting fix that will make sense to integrate) 

thanks a lot.

**Comment by allan-simon** [comment]
my bad I think it's what you already did , right ?

**Comment by kamichidu** [comment]
shougo already merged other forks, only easy to merge. i'm re-creating brandnew version of javacomplete.

i have some plan:
1. refactoring for easy to re-create
2. delete some uninteresting feature
3. re-create this, faster, responsible and frexible one

**Comment by kamichidu** [comment]
but, unfourtunately, now i have no time to do it. when i have enough i'll do it.

**Comment by allan-simon** [comment]
ok I understand どうもありがとう =)

**Comment by kamichidu** [comment]
your welcome :)
thanks!
