### ISSUE TITLE
Javaparser seems to be broken.

### ISSUE THREAD

**Issue by leonschreuder** [Shougo/javacomplete#3]
I've been using javacomplete for a while now, trying real hard to get it to behave. It just seemed to work normally but randomly hanging on completion. Now I think I've figured out the problem: The java-parser is just broken. Every time I add a raw sources path it breaks on autocompletion (hangs indefinitely). Even when no source paths are added to javacomplete, but I try to use the return value of a method in another class, it hangs again. Example of this:

``` java
    public class TestSource {
        public void doSomething() {
            System.out.println("Done");
        }
    }

    //Other file
    public class TestEdit {
        public void callOnOther() {
            TestSource source = new TestSource();
            source. //hangs here
        }
    }
```

The reflector.java seems to work like it should, because all class files or jars I add are getting completed normally.

**Comment by Shougo** [comment]
Thank you.  But this plugin is not maintained.  I think javaparser is broken too.
Pull Request is wellcome.

**Comment by Shougo** [comment]
I think the repository should be archived.
